### ISSUE TITLE
Automatically determine dimensions for `aq.ArrayVar` declaration

### ISSUE THREAD

**Issue by rmshaffer** [amazon-braket/autoqasm#13]
Today the `dimensions` kwarg is required when declaring an `aq.ArrayVar`. For example:
```
aq.ArrayVar([1, 2, 3], dimensions=[3])
```
We should be able to automatically infer `dimensions` if an initial value is defined. So the code becomes just:
```
aq.ArrayVar([1, 2, 3])
```
Optionally, we may remove the `dimensions` kwarg altogether, and force the user to always specify an initial value.

**Comment by rmshaffer** [comment]
@Yash-10, thank you for the contribution! Can you please confirm that you'd like me to assign this issue to you?

**Comment by Yash-10** [comment]
Thank you @rmshaffer! Sure, I'd like to be assigned to this issue.
